# Exception

Yao integrates `Exception` internally, which can throw an exception in any JS file and terminate the program.

## Example

Exception throws an exception:

```javascript
throw new Exception("Page not found", 404);
```

<Div style={{ display: "flex", justifyContent: "space-between" }}>
  <Link type="prev" title="Log" link="Manual/JS API/Log"></Link>
  <Link type="next" title="Query" link="Manual/JS API/Query"></Link>
</Div>
